<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HOFM65N" failures="1" tests="2" name="zeroBankTests.AccountSummaryCreditCardAccounts" time="3.248" errors="0" timestamp="2021-02-07T22:19:16 EET" skipped="0">
  <testcase classname="zeroBankTests.AccountSummaryCreditCardAccounts" name="CreditCardVerfyValid" time="3.208"/>
  <system-out>
Starting test method:CreditCardVerfyValid  Enter value : username  Enter value : password All Elements on Account Summary Page are displayed All Elements on Account Summary Page are displayed VISA 4485-5368-3381-1879 CreditCardVerfyValid is Passed  </system-out>
  <testcase classname="zeroBankTests.AccountSummaryCreditCardAccounts" name="CreditCardVerfyInvalid" time="0.040">
    <failure message="expected [VISA 4485-5368-3381-1111] but found [VISA 4485-5368-3381-1879]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [VISA 4485-5368-3381-1111] but found [VISA 4485-5368-3381-1879]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at zeroBankTests.AccountSummaryCreditCardAccounts.CreditCardVerfyInvalid(AccountSummaryCreditCardAccounts.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CreditCardVerfyInvalid -->
  <system-out>
Starting test method:CreditCardVerfyInvalid CreditCardVerfyInvalid is Failed Click to see Screenshot <a href=C:\Users\plame\eclipse-workspace\ZeroBankProject\screenshots\Sun_Feb_07_22_19_13_EET_2021.png></a> <br>  <img src='C:\Users\plame\eclipse-workspace\ZeroBankProject\screenshots\Sun_Feb_07_22_19_13_EET_2021.png' height='200' width='200' /><br> <a target="_blank" href=C:\Users\plame\eclipse-workspace\ZeroBankProject\screenshots\Sun_Feb_07_22_19_13_EET_2021.png>Screenshot</a>  </system-out>
</testsuite> <!-- zeroBankTests.AccountSummaryCreditCardAccounts -->
